version: "3"

services:
  jenkins:
    image: jenkins/jenkins:jdk17  # Specify the latest weekly Jenkins image
    ports:
      - "8080:8080"  # Map Jenkins container port to host
    networks:
      - my_network

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"  # Map SonarQube container port to host
    networks:
      - my_network
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

networks:
  my_network:

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

